function T = fxp_types(dt) %#codegen
%CR_FXP_TYPES  Shared fixed-point type table for bps_fxp and viterbiViterbi_fxp.
%
%   T = fxp_types(dt)
%
%   Returns a struct of fi prototype objects that define every fixed-point
%   type used inside bps_fxp and viterbiViterbi_fxp.
%
%   Supported configurations
%     'double'              - all types are double (floating-point baseline / reference)
%     'single'              - all types are single
%     'fixed16'             - 16-bit signal & phase, 32-bit accumulator
%     'fixed32'             - 32-bit signal & phase, 64-bit accumulator
%     struct('WL',wl,'FL',fl) - custom: uniform word length wl, fraction length fl
%
%   Fields
%     T.x      - input / output signal (complex QAM samples, rotation factors)
%     T.w      - filter coefficients (VV filter; unused in BPS but provided
%                for interface parity)
%     T.theta  - phase angle type (must accommodate ±pi ≈ ±3.14)
%     T.acc    - wide accumulator for pilot correlation inner products
%
%   Numerical design notes
%
%   Signal range
%     Unit-average-power QAM symbols and unit-magnitude rotation factors
%     both have |z| ≈ 1.  WL=32 / FL=4 gives range ±124, LSB ≈ 3.9e-3.
%
%   Phase range
%     Test phases span ±pi/4; unwrapped phase stays within ±pi ≈ ±3.14.
%     WL=32 / FL=24 gives range ±4, LSB ≈ 3.7e-9 — amply precise.
%
%   Accumulator width (fixed32)
%     One pilot product per block; no summation across symbols needed.
%     A 64-bit accumulator with FL=24 prevents overflow and preserves
%     precision through the cordicangle call.
%
%   SpecifyPrecision fimath
%     All fi arithmetic uses SpecifyPrecision so every product and sum is
%     truncated to a known WL/FL with no implicit bit growth — required for
%     deterministic codegen behaviour.

    if isstruct(dt)
        wl = dt.WL;
        fl = dt.FL;
        F = fimath( ...
            'RoundingMethod',        'Floor', ...
            'OverflowAction',        'Wrap',  ...
            'ProductMode',           'SpecifyPrecision', ...
            'ProductWordLength',      wl,     ...
            'ProductFractionLength',  fl,     ...
            'SumMode',               'SpecifyPrecision', ...
            'SumWordLength',          wl,     ...
            'SumFractionLength',      fl);
        T.x     = fi([], 1, wl, fl, F);
        T.w     = fi([], 1, wl, fl, F);
        T.theta = fi([], 1, wl, fl, F);
        T.acc   = fi([], 1, wl, fl, F);
        return;
    end

    switch dt
        %% ==============================================================
        case 'double'
            T.x     = double([]);
            T.w     = double([]);
            T.theta = double([]);
            T.acc   = double([]);

        %% ==============================================================
        case 'single'
            T.x     = single([]);
            T.w     = single([]);
            T.theta = single([]);
            T.acc   = single([]);

        %% ==============================================================
        case 'fixed16'
            % --- Signal & coefficient type: 32-bit, FL = 4 -----------
            %   Range ±124, LSB = 2^{-4} ≈ 3.9e-3.
            Fx = fimath( ...
                'RoundingMethod',        'Floor', ...
                'OverflowAction',        'Wrap',  ...
                'ProductMode',           'SpecifyPrecision', ...
                'ProductWordLength',      32,     ...
                'ProductFractionLength',  4,      ...
                'SumMode',               'SpecifyPrecision', ...
                'SumWordLength',          32,     ...
                'SumFractionLength',      4);

            % --- Phase / angle type: 32-bit, FL = 4 ------------------
            %   Same range; ±124 comfortably fits ±pi ≈ ±3.14.
            Fth = fimath( ...
                'RoundingMethod',        'Floor', ...
                'OverflowAction',        'Wrap',  ...
                'ProductMode',           'SpecifyPrecision', ...
                'ProductWordLength',      32,     ...
                'ProductFractionLength',  4,      ...
                'SumMode',               'SpecifyPrecision', ...
                'SumWordLength',          32,     ...
                'SumFractionLength',      4);

            % --- Accumulator: 32-bit, FL = 4 -------------------------
            Facc = fimath( ...
                'RoundingMethod',        'Floor', ...
                'OverflowAction',        'Wrap',  ...
                'ProductMode',           'SpecifyPrecision', ...
                'ProductWordLength',      32,     ...
                'ProductFractionLength',  4,      ...
                'SumMode',               'SpecifyPrecision', ...
                'SumWordLength',          32,     ...
                'SumFractionLength',      4);

            T.x     = fi([], 1, 32, 4, Fx);
            T.w     = fi([], 1, 32, 4, Fx);
            T.theta = fi([], 1, 32, 4, Fth);
            T.acc   = fi([], 1, 32, 4, Facc);

        %% ==============================================================
        case 'fixed32'
            % --- Signal & coefficient type: 32-bit, FL = 24 ----------
            %   Range ±256, LSB = 2^{-24} ≈ 6e-4.
            Fx = fimath( ...
                'RoundingMethod',        'Floor', ...
                'OverflowAction',        'Wrap',  ...
                'ProductMode',           'SpecifyPrecision', ...
                'ProductWordLength',      32,     ...
                'ProductFractionLength',  16,     ...
                'SumMode',               'SpecifyPrecision', ...
                'SumWordLength',          32,     ...
                'SumFractionLength',      16);

            % --- Phase / angle type: 32-bit, FL = 24 -----------------
            %   Range ±4 fits ±pi,  LSB ≈ 3.7e-9.
            Fth = fimath( ...
                'RoundingMethod',        'Floor', ...
                'OverflowAction',        'Wrap',  ...
                'ProductMode',           'SpecifyPrecision', ...
                'ProductWordLength',      32,     ...
                'ProductFractionLength',  16,     ...
                'SumMode',               'SpecifyPrecision', ...
                'SumWordLength',          32,     ...
                'SumFractionLength',      16);

            % --- Accumulator: 64-bit, FL = 24 ------------------------
            %   Handles the single-symbol pilot product without overflow.
            Facc = fimath( ...
                'RoundingMethod',        'Floor', ...
                'OverflowAction',        'Wrap',  ...
                'ProductMode',           'SpecifyPrecision', ...
                'ProductWordLength',      32,     ...
                'ProductFractionLength',  16,     ...
                'SumMode',               'SpecifyPrecision', ...
                'SumWordLength',          32,     ...
                'SumFractionLength',      16);

            T.x     = fi([], 1, 32, 16, Fx);
            T.w     = fi([], 1, 32, 16, Fx);
            T.theta = fi([], 1, 32, 16, Fth);
            T.acc   = fi([], 1, 32, 16, Facc);

        otherwise
            error('fxp_types:BadType', ...
                'Unknown type configuration ''%s''.', dt);
    end
end
