function T = fxp_types(dt) %#codegen
%CR_FXP_TYPES  Shared fixed-point type table for bps_fxp and viterbiViterbi_fxp.
%
%   T = fxp_types(dt)
%
%   Returns a struct of fi prototype objects that define every fixed-point
%   type used inside bps_fxp and viterbiViterbi_fxp.
%
%   Supported configurations
%     'double'   - all types are double (floating-point baseline / reference)
%     'single'   - all types are single
%     'fixed16'  - 16-bit signal & phase, 32-bit accumulator
%     'fixed32'  - 32-bit signal & phase, 64-bit accumulator
%
%   Fields
%     T.x      - input / output signal (complex QAM samples, rotation factors)
%     T.w      - filter coefficients (VV filter; unused in BPS but provided
%                for interface parity)
%     T.theta  - phase angle type (must accommodate ±pi ≈ ±3.14)
%     T.acc    - wide accumulator for pilot correlation inner products
%
%   Numerical design notes
%
%   Signal range
%     Unit-average-power QAM symbols and unit-magnitude rotation factors
%     both have |z| ≈ 1.  WL=32 / FL=8 gives range ±128, LSB ≈ 3.9e-3.
%
%   Phase range
%     Test phases span ±pi/4; unwrapped phase stays within ±pi ≈ ±3.14.
%     WL=32 / FL=28 gives range ±8, LSB ≈ 3.7e-9 — amply precise.
%
%   Accumulator width (fixed32)
%     One pilot product per block; no summation across symbols needed.
%     A 64-bit accumulator with FL=28 prevents overflow and preserves
%     precision through the cordicangle call.
%
%   SpecifyPrecision fimath
%     All fi arithmetic uses SpecifyPrecision so every product and sum is
%     truncated to a known WL/FL with no implicit bit growth — required for
%     deterministic codegen behaviour.

    switch dt
        %% ==============================================================
        case 'double'
            T.x     = double([]);
            T.w     = double([]);
            T.theta = double([]);
            T.acc   = double([]);

        %% ==============================================================
        case 'single'
            T.x     = single([]);
            T.w     = single([]);
            T.theta = single([]);
            T.acc   = single([]);

        %% ==============================================================
        case 'fixed16'
            % --- Signal & coefficient type: 32-bit, FL = 8 -----------
            %   Range ±128, LSB = 2^{-8} ≈ 3.9e-3.
            Fx = fimath( ...
                'RoundingMethod',        'Floor', ...
                'OverflowAction',        'Wrap',  ...
                'ProductMode',           'SpecifyPrecision', ...
                'ProductWordLength',      32,     ...
                'ProductFractionLength',  8,      ...
                'SumMode',               'SpecifyPrecision', ...
                'SumWordLength',          32,     ...
                'SumFractionLength',      8);

            % --- Phase / angle type: 32-bit, FL = 8 ------------------
            %   Same range; ±128 comfortably fits ±pi ≈ ±3.14.
            Fth = fimath( ...
                'RoundingMethod',        'Floor', ...
                'OverflowAction',        'Wrap',  ...
                'ProductMode',           'SpecifyPrecision', ...
                'ProductWordLength',      32,     ...
                'ProductFractionLength',  8,      ...
                'SumMode',               'SpecifyPrecision', ...
                'SumWordLength',          32,     ...
                'SumFractionLength',      8);

            % --- Accumulator: 32-bit, FL = 8 -------------------------
            Facc = fimath( ...
                'RoundingMethod',        'Floor', ...
                'OverflowAction',        'Wrap',  ...
                'ProductMode',           'SpecifyPrecision', ...
                'ProductWordLength',      32,     ...
                'ProductFractionLength',  8,      ...
                'SumMode',               'SpecifyPrecision', ...
                'SumWordLength',          32,     ...
                'SumFractionLength',      8);

            T.x     = fi([], 1, 32, 8, Fx);
            T.w     = fi([], 1, 32, 8, Fx);
            T.theta = fi([], 1, 32, 8, Fth);
            T.acc   = fi([], 1, 32, 8, Facc);

        %% ==============================================================
        case 'fixed32'
            % --- Signal & coefficient type: 32-bit, FL = 24 ----------
            %   Range ±256, LSB = 2^{-24} ≈ 6e-8.
            Fx = fimath( ...
                'RoundingMethod',        'Floor', ...
                'OverflowAction',        'Wrap',  ...
                'ProductMode',           'SpecifyPrecision', ...
                'ProductWordLength',      32,     ...
                'ProductFractionLength',  16,     ...
                'SumMode',               'SpecifyPrecision', ...
                'SumWordLength',          32,     ...
                'SumFractionLength',      16);

            % --- Phase / angle type: 32-bit, FL = 28 -----------------
            %   Range ±8 fits ±pi,  LSB ≈ 3.7e-9.
            Fth = fimath( ...
                'RoundingMethod',        'Floor', ...
                'OverflowAction',        'Wrap',  ...
                'ProductMode',           'SpecifyPrecision', ...
                'ProductWordLength',      32,     ...
                'ProductFractionLength',  16,     ...
                'SumMode',               'SpecifyPrecision', ...
                'SumWordLength',          32,     ...
                'SumFractionLength',      16);

            % --- Accumulator: 64-bit, FL = 28 ------------------------
            %   Handles the single-symbol pilot product without overflow.
            Facc = fimath( ...
                'RoundingMethod',        'Floor', ...
                'OverflowAction',        'Wrap',  ...
                'ProductMode',           'SpecifyPrecision', ...
                'ProductWordLength',      32,     ...
                'ProductFractionLength',  16,     ...
                'SumMode',               'SpecifyPrecision', ...
                'SumWordLength',          32,     ...
                'SumFractionLength',      16);

            T.x     = fi([], 1, 32, 16, Fx);
            T.w     = fi([], 1, 32, 16, Fx);
            T.theta = fi([], 1, 32, 16, Fth);
            T.acc   = fi([], 1, 32, 16, Facc);

        otherwise
            error('fxp_types:BadType', ...
                'Unknown type configuration ''%s''.', dt);
    end
end
