function T = cr_bps_fxp_types(dt) %#codegen
%CR_BPS_FXP_TYPES  Data-type table for cr_bps_fxp.
%
%   T = cr_bps_fxp_types(dt)
%
%   Returns a struct of fi prototype objects that define every fixed-point
%   type used inside cr_bps_fxp.
%
%   Supported configurations
%     'double'   - all types are double (floating-point baseline / reference)
%     'single'   - all types are single
%     'fixed16'  - 16-bit signal & phase, 32-bit accumulator
%     'fixed32'  - 32-bit signal & phase, 64-bit accumulator
%
%   Fields
%     T.x      - input / output signal (complex QAM samples, rotation factors)
%     T.w      - reserved for filter coefficients (unused in BPS; provided
%                for interface parity with cr_viterbiViterbi_fxp_types)
%     T.theta  - phase angle type (must accommodate ±pi ≈ ±3.14)
%     T.acc    - wide accumulator for pilot correlation inner products
%
%   Numerical design notes
%
%   Signal range
%     BPS operates on unit-average-power QAM symbols (|z| ≈ 1 with noise).
%     The rotation factors exp(-j*theta) have unit magnitude.
%     Rotated samples therefore also have magnitude ≈ 1.
%     FL = 12 on a 16-bit word gives range ±8, LSB ≈ 2.4e-4 — comfortable.
%
%   Phase range
%     BPS test phases span ±pi/4 (≈ ±0.785).  The unwrapped phase can reach
%     ±pi but not beyond, so the same FL = 12 / range ±8 covers T.theta.
%     (Same rationale as cr_viterbiViterbi_fxp_types.)
%
%   Accumulator width
%     The BPS *metric* (sum of squared distances) is kept in double — see
%     cr_bps_fxp.  T.acc is only used for the pilot correlation sum:
%       max terms = NPol * PilotLen products, each ≤ |z|^2 ≈ 1
%     16 extra integer bits (32-bit FL12 acc) handle up to 2^16 = 65536
%     terms without overflow — far more than any realistic pilot length.
%
%   SpecifyPrecision fimath
%     All fi arithmetic uses SpecifyPrecision so every product and sum is
%     truncated to a known WL/FL with no implicit bit growth — required for
%     deterministic codegen behaviour.

    switch dt
        %% ==============================================================
        case 'double'
            T.x     = double([]);
            T.w     = double([]);
            T.theta = double([]);
            T.acc   = double([]);

        %% ==============================================================
        case 'single'
            T.x     = single([]);
            T.w     = single([]);
            T.theta = single([]);
            T.acc   = single([]);

        %% ==============================================================
        case 'fixed16'
            % --- Signal & rotation-factor type: 16-bit, FL = 12 ------
            %   Range ±8,  LSB = 2^{-12} ≈ 2.4e-4
            %   Covers unit-power QAM samples and unit-magnitude exp(-jθ).
            Fx = fimath( ...
                'RoundingMethod',        'Floor', ...
                'OverflowAction',        'Wrap',  ...
                'ProductMode',           'SpecifyPrecision', ...
                'ProductWordLength',      32,     ...
                'ProductFractionLength',  12,     ...
                'SumMode',               'SpecifyPrecision', ...
                'SumWordLength',          16,     ...
                'SumFractionLength',      12);

            % --- Phase / angle type: 16-bit, FL = 12 -----------------
            %   Same range as Fx; ±8 comfortably fits ±pi ≈ ±3.14.
            Fth = fimath( ...
                'RoundingMethod',        'Floor', ...
                'OverflowAction',        'Wrap',  ...
                'ProductMode',           'SpecifyPrecision', ...
                'ProductWordLength',      32,     ...
                'ProductFractionLength',  12,     ...
                'SumMode',               'SpecifyPrecision', ...
                'SumWordLength',          32,     ...
                'SumFractionLength',      12);

            % --- Accumulator: 32-bit, FL = 12 ------------------------
            %   Extra 16 integer bits absorb NPol*PilotLen pilot
            %   correlation products without overflow.
            Facc = fimath( ...
                'RoundingMethod',        'Floor', ...
                'OverflowAction',        'Wrap',  ...
                'ProductMode',           'SpecifyPrecision', ...
                'ProductWordLength',      32,     ...
                'ProductFractionLength',  12,     ...
                'SumMode',               'SpecifyPrecision', ...
                'SumWordLength',          32,     ...
                'SumFractionLength',      12);

            T.x     = fi([], 1, 32, 12, Fx);
            T.w     = fi([], 1, 32, 12, Fx);    % parity; unused in BPS
            T.theta = fi([], 1, 32, 12, Fth);
            T.acc   = fi([], 1, 32, 12, Facc);

        %% ==============================================================
        case 'fixed32'
            % --- Signal & rotation-factor type: 32-bit, FL = 24 ------
            %   Range ±256, LSB = 2^{-24} ≈ 6e-8
            Fx = fimath( ...
                'RoundingMethod',        'Floor', ...
                'OverflowAction',        'Wrap',  ...
                'ProductMode',           'SpecifyPrecision', ...
                'ProductWordLength',      32,     ...
                'ProductFractionLength',  24,     ...
                'SumMode',               'SpecifyPrecision', ...
                'SumWordLength',          32,     ...
                'SumFractionLength',      24);

            % --- Phase / angle type: 32-bit, FL = 28 -----------------
            %   Range ±8 fits ±pi,  LSB ≈ 3.7e-9
            Fth = fimath( ...
                'RoundingMethod',        'Floor', ...
                'OverflowAction',        'Wrap',  ...
                'ProductMode',           'SpecifyPrecision', ...
                'ProductWordLength',      32,     ...
                'ProductFractionLength',  28,     ...
                'SumMode',               'SpecifyPrecision', ...
                'SumWordLength',          32,     ...
                'SumFractionLength',      28);

            % --- Accumulator: 64-bit, FL = 28 ------------------------
            %   Handles arbitrarily long pilot sequences without saturation.
            Facc = fimath( ...
                'RoundingMethod',        'Floor', ...
                'OverflowAction',        'Wrap',  ...
                'ProductMode',           'SpecifyPrecision', ...
                'ProductWordLength',      64,     ...
                'ProductFractionLength',  28,     ...
                'SumMode',               'SpecifyPrecision', ...
                'SumWordLength',          64,     ...
                'SumFractionLength',      28);

            T.x     = fi([], 1, 32, 24, Fx);
            T.w     = fi([], 1, 32, 24, Fx);
            T.theta = fi([], 1, 32, 28, Fth);
            T.acc   = fi([], 1, 64, 28, Facc);

        otherwise
            error('cr_bps_fxp_types:BadType', ...
                'Unknown type configuration ''%s''.', dt);
    end
end